url: http://brandeisxdemandware.github.io.

# Site settings
title: Brandeis X Demandware
email: wesley.chin0919@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffa3b9
  secondary: ff84a3
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Wesley
  pic: 1
  position: Computer Science & Neuroscience <br> 2017'
  social:
    - title: github
      url: https://github.com/WesleyyC
    - title: linkedin
      url: https://www.linkedin.com/in/wesleychin0919

- name: Shimon
  pic: 2
  position: Computer Science & Economic <br> 2016'
  social:
    - title: github
      url: https://github.com/shimonm
    - title: linkedin
      url: https://www.linkedin.com/in/shimonmazor

- name: Brian
  pic: 3
  position: Computer Science & Politic <br> 2016'
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/brian-luk-0a494a90

- name: Jing
  pic: 4
  position: Computer Science MS. <br> 2016'
  social:
    - title: github
      url: https://github.com/ginnyzou2015
    - title: linkedin
      url: https://www.linkedin.com/in/jing-zou-baa2ba46

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/BrandeisXDemandware

# Postal address (add as many lines as necessary)
address:
  - line: 415 South Street
  - line: Waltham, MA 

# Build settings
markdown: kramdown
permalink: pretty